# Generated by Django 2.2 on 2022-04-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('Fullname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='default.png', upload_to='Experts/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=100)),
                ('pkg_price', models.BigIntegerField()),
                ('pkg_desc', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(default='', upload_to='Photo_Gallary/')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Image', models.ImageField(default='', upload_to='Service_Cat_Image/')),
                ('CategoryName', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField(default=0)),
                ('Password', models.CharField(max_length=50)),
                ('status', models.CharField(default='Inactice', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(max_length=100)),
                ('MRP', models.BigIntegerField()),
                ('Price', models.BigIntegerField()),
                ('Description', models.TextField(max_length=255)),
                ('Service_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Service_Category')),
            ],
        ),
    ]
